import Vue from 'vue'

export default ({
    state: {
        menus: [
            {
              id: 1,
              name: "Biryani Rice",
              description: "Biryani Rice is basically a spiced rice, that is, basmati rice cooked with choicest of spices and finished with some fried onions, nuts and fresh herbs. However, there are many variations of this biryani chawal recipe.",
              sku: "1101301",
              image: "biryani-cover.jpg",
              category_id: 7,
              attributes: null,
              price: "30000.00",
              tax_id: 1,
              discount: "0.00",
              discount_type: null,
              discount_start: null,
              discount_end: null,
              available_time_start: "15:00:00",
              available_time_end: "21:00:00",
              waiting_time_from: 15,
              waiting_time_to: 30,
              veg: 0,
              status: 1,
              restaurant_id: 1,
              order_count: 127,
              rating_count: 0,
              avg_rating: "0",
              slug: "biryani_rice",
              created_at: "2023-05-15T05:36:47.000000Z",
              updated_at: "2023-05-15T05:36:47.000000Z"
            },
            {
              id: 2,
              name: "Nasi Goreng",
              description: "Nasi Goreng simply fry cooked rice along with basic ingredients that include a garlic, shallots, chili and sweet soy sauce. You can also break an egg then stir-fry this together with the rice and shredded chicken pieces or meat.",
              sku: "1101302",
              image: "fried-rice-cover.jpg",
              category_id: 7,
              attributes: null,
              price: "15000.00",
              tax_id: 1,
              discount: "0.00",
              discount_type: null,
              discount_start: null,
              discount_end: null,
              available_time_start: "15:00:00",
              available_time_end: "21:00:00",
              waiting_time_from: 15,
              waiting_time_to: 30,
              veg: 0,
              status: 1,
              restaurant_id: 1,
              order_count: 59,
              rating_count: 0,
              avg_rating: "0",
              slug: "nasi_goreng",
              created_at: "2023-05-15T05:36:47.000000Z",
              updated_at: "2023-05-15T05:36:47.000000Z"
            },
            {
              id: 3,
              name: "Sate",
              description: "Sate, juicy slices of marinated meat on thin bamboo skewers grilled to perfection on a charcoal open fire and accompanied by a delectably savoury sauce - it is no wonder that this dish is one of President Barack Obama’s childhood favourites.Sate (or more commonly known as Satay) is undoubtedly one of Indonesia most famous dishes.",
              sku: "1101303",
              image: "sate-cover.jpg",
              category_id: 4,
              attributes: null,
              price: "15000.00",
              tax_id: 1,
              discount: "0.00",
              discount_type: null,
              discount_start: null,
              discount_end: null,
              available_time_start: "15:00:00",
              available_time_end: "21:00:00",
              waiting_time_from: 15,
              waiting_time_to: 30,
              veg: 0,
              status: 1,
              restaurant_id: 1,
              order_count: 201,
              rating_count: 0,
              avg_rating: "0",
              slug: "sate",
              created_at: "2023-05-15T05:36:47.000000Z",
              updated_at: "2023-05-15T05:36:47.000000Z"
            },
            {
              id: 4,
              name: "Soto",
              description: "Soto is one of Indonesia's culinary categories that includes soupy dishes made from meat or vegetable broth and contains shredded meat or chicken, vermicelli, and bean sprouts, among other ingredients. It is usually served with rice or rice cake.",
              sku: "1101304",
              image: "soto-cover.jpg",
              category_id: 4,
              attributes: null,
              price: "19000.00",
              tax_id: 1,
              discount: "0.00",
              discount_type: null,
              discount_start: null,
              discount_end: null,
              available_time_start: "15:00:00",
              available_time_end: "21:00:00",
              waiting_time_from: 15,
              waiting_time_to: 35,
              veg: 0,
              status: 1,
              restaurant_id: 1,
              order_count: 0,
              rating_count: 0,
              avg_rating: "0",
              slug: "soto",
              created_at: "2023-05-15T05:36:47.000000Z",
              updated_at: "2023-05-15T05:36:47.000000Z"
            },
            {
              id: 5,
              name: "Nasi Liwet",
              description: "Nasi liwet is a typical Indonesian rice dish cooked with coconut milk, chicken stock, and spices[1]. Steamed rice is usually cooked in water, but nasi liwet is rice cooked with coconut milk, chicken broth, bay leaves and lemongrass, giving the rice a rich, aromatic and savory taste.",
              sku: "1101305",
              image: "nasi-liwet-cover.jpg",
              category_id: 7,
              attributes: null,
              price: "32000.00",
              tax_id: 1,
              discount: "0.00",
              discount_type: null,
              discount_start: null,
              discount_end: null,
              available_time_start: "15:00:00",
              available_time_end: "21:00:00",
              waiting_time_from: 10,
              waiting_time_to: 25,
              veg: 0,
              status: 1,
              restaurant_id: 1,
              order_count: 0,
              rating_count: 0,
              avg_rating: "0",
              slug: "nasi_liwet",
              created_at: "2023-05-15T05:36:47.000000Z",
              updated_at: "2023-05-15T05:36:47.000000Z"
            },
            {
              id: 6,
              name: "Ayam Penyet",
              description: "Ayam Penyet is an Indonesian fried chicken dish, particularly Javanese, which consists of pulverizing fried chicken using a mortar and pestle to soften it, served with chili sauce, cucumber slices, fried tofu and tempeh.",
              sku: "1101306",
              image: "ayam-penyet-cover.jpg",
              category_id: 7,
              attributes: null,
              price: "31000.00",
              tax_id: 1,
              discount: "15.00",
              discount_type: "percentage",
              discount_start: "2023-05-01",
              discount_end: "2023-06-30",
              available_time_start: "15:00:00",
              available_time_end: "21:00:00",
              waiting_time_from: 10,
              waiting_time_to: 25,
              veg: 0,
              status: 1,
              restaurant_id: 1,
              order_count: 0,
              rating_count: 0,
              avg_rating: "0",
              slug: "ayam_penyet",
              created_at: "2023-05-15T05:36:47.000000Z",
              updated_at: "2023-05-15T05:36:47.000000Z"
            },
            {
              id: 7,
              name: "Nasi Rendang",
              description: "Rendang or Randang/Rondang in the Minangkabau language (Jawi: رندڠ) is a meat-based Minangkabau dish originating from West Sumatra, Indonesia. Cuisine is processed meat (usually beef or buffalo) or eggs cooked at low temperatures for a long time using various spices and coconut milk.",
              sku: "1101307",
              image: "nasi-rendang-cover.jpg",
              category_id: 7,
              attributes: null,
              price: "36000.00",
              tax_id: 1,
              discount: "20.00",
              discount_type: "percentage",
              discount_start: "2023-05-01",
              discount_end: "2023-06-30",
              available_time_start: "15:00:00",
              available_time_end: "21:00:00",
              waiting_time_from: 10,
              waiting_time_to: 20,
              veg: 0,
              status: 1,
              restaurant_id: 1,
              order_count: 0,
              rating_count: 0,
              avg_rating: "0",
              slug: "nasi_rendang",
              created_at: "2023-05-15T05:36:47.000000Z",
              updated_at: "2023-05-15T05:36:47.000000Z"
            },
            [
                {
                  id: 8,
                  name: "Tom Yum",
                  description: "Tom Yum is one of the best known Thai dishes, a spicy, sour, and aromatic soup that is traditionally served with rice. It consists of shallots, lemongrass, fish sauce, minced fresh ginger or galangal, shrimps, mushrooms, kaffir lime leaves, lime juice, and minced Thai chili peppers.",
                  sku: "1101308",
                  image: "tom-yum-cover.jpg",
                  category_id: 4,
                  attributes: null,
                  price: "38000.00",
                  tax_id: 1,
                  discount: "0.00",
                  discount_type: null,
                  discount_start: null,
                  discount_end: null,
                  available_time_start: "15:00:00",
                  available_time_end: "21:00:00",
                  waiting_time_from: 10,
                  waiting_time_to: 20,
                  veg: 0,
                  status: 1,
                  restaurant_id: 2,
                  order_count: 0,
                  rating_count: 0,
                  avg_rating: "0",
                  slug: "tom_yum",
                  created_at: "2023-05-15T05:36:47.000000Z",
                  updated_at: "2023-05-15T05:36:47.000000Z"
                },
                {
                  id: 9,
                  name: "Tongseng",
                  description: "Tongseng is an Indonesian goat meat, mutton or beef stew dish in curry-like soup, with vegetables and kecap manis (sweet soy sauce). Tongseng is commonly found in Indonesian region of Central Java; from Surakarta to Yogyakarta.",
                  sku: "1101309",
                  image: "tongseng-cover.jpg",
                  category_id: 4,
                  attributes: null,
                  price: "32000.00",
                  tax_id: 1,
                  discount: "0.00",
                  discount_type: null,
                  discount_start: null,
                  discount_end: null,
                  available_time_start: "15:00:00",
                  available_time_end: "21:00:00",
                  waiting_time_from: 10,
                  waiting_time_to: 20,
                  veg: 0,
                  status: 1,
                  restaurant_id: 2,
                  order_count: 0,
                  rating_count: 0,
                  avg_rating: "0",
                  slug: "tongseng",
                  created_at: "2023-05-15T05:36:47.000000Z",
                  updated_at: "2023-05-15T05:36:47.000000Z"
                },
                {
                  id: 10,
                  name: "Rawon",
                  description: "Rawon (Javanese: ꦫꦮꦺꦴꦤ꧀) is an Indonesian beef soup. Originating from East Java, rawon utilizes the black keluak nut as the main seasoning, which gives a dark color and nutty flavor to the soup.",
                  sku: "1101310",
                  image: "rawon-cover.jpg",
                  category_id: 4,
                  attributes: null,
                  price: "33000.00",
                  tax_id: 1,
                  discount: "0.00",
                  discount_type: null,
                  discount_start: null,
                  discount_end: null,
                  available_time_start: "15:00:00",
                  available_time_end: "21:00:00",
                  waiting_time_from: 10,
                  waiting_time_to: 20,
                  veg: 0,
                  status: 1,
                  restaurant_id: 2,
                  order_count: 0,
                  rating_count: 0,
                  avg_rating: "0",
                  slug: "rawon",
                  created_at: "2023-05-15T05:36:47.000000Z",
                  updated_at: "2023-05-15T05:36:47.000000Z"
                },
                {
                  id: 11,
                  name: "Vietnamse Beef pho",
                  description: "A bowl of beef phở (pronounced “fuh“) consists of soft slippery noodles in a hearty, beefy yet fragrant broth and beef slices of your choice. In traditional Vietnamese cooking, pho broth is typically simmered for many hours in order to create that rich, layered, cozy blend of flavors that we all know and love.",
                  sku: "1101311",
                  image: "vietnamese-beef-pho-cover.jpg",
                  category_id: 4,
                  attributes: null,
                  price: "39000.00",
                  tax_id: 1,
                  discount: "15.00",
                  discount_type: "percentage",
                  discount_start: "2023-05-01",
                  discount_end: "2023-06-30",
                  available_time_start: "15:00:00",
                  available_time_end: "21:00:00",
                  waiting_time_from: 10,
                  waiting_time_to: 20,
                  veg: 0,
                  status: 1,
                  restaurant_id: 2,
                  order_count: 0,
                  rating_count: 0,
                  avg_rating: "0",
                  slug: "vietnamse_beef_pho",
                  created_at: "2023-05-15T05:36:47.000000Z",
                  updated_at: "2023-05-15T05:36:47.000000Z"
                },
                {
                  id: 12,
                  name: "Bakso",
                  description: "Bakso adalah jenis bola daging yang lazim ditemukan pada masakan Indonesia. Bakso umumnya dibuat dari campuran daging sapi giling dan tepung tapioka, tetapi ada juga bakso yang terbuat dari daging ayam, babi, ikan, udang bahkan daging kerbau.",
                  sku: "1101312",
                  image: "bakso-cover.jpg",
                  category_id: 4,
                  attributes: null,
                  price: "18000.00",
                  tax_id: 1,
                  discount: "15.00",
                  discount_type: "percentage",
                  discount_start: "2023-05-01",
                  discount_end: "2023-06-30",
                  available_time_start: "15:00:00",
                  available_time_end: "21:00:00",
                  waiting_time_from: 10,
                  waiting_time_to: 20,
                  veg: 0,
                  status: 1,
                  restaurant_id: 2,
                  order_count: 0,
                  rating_count: 0,
                  avg_rating: "0",
                  slug: "bakso",
                  created_at: "2023-05-15T05:36:47.000000Z",
                  updated_at: "2023-05-15T05:36:47.000000Z"
                }
            ]
        ],
        categories: [
            {
              id: 1,
              name: "Sandwich",
              image: "sandwich.png",
              parent_id: null,
              position: null,
              status: 1,
              priority: 1,
              slug: "sandwich",
              created_at: "2023-05-15T05:36:47.000000Z",
              updated_at: "2023-05-15T05:36:47.000000Z"
            },
            {
              id: 2,
              name: "Coffee",
              image: "coffee.png",
              parent_id: null,
              position: null,
              status: 1,
              priority: 1,
              slug: "coffee",
              created_at: "2023-05-15T05:36:47.000000Z",
              updated_at: "2023-05-15T05:36:47.000000Z"
            },
            {
              id: 3,
              name: "Pizza",
              image: "pizaa.png",
              parent_id: null,
              position: null,
              status: 1,
              priority: 1,
              slug: "pizza",
              created_at: "2023-05-15T05:36:47.000000Z",
              updated_at: "2023-05-15T05:36:47.000000Z"
            },
            {
              id: 4,
              name: "Meat",
              image: "meat.png",
              parent_id: null,
              position: null,
              status: 1,
              priority: 1,
              slug: "meat",
              created_at: "2023-05-15T05:36:47.000000Z",
              updated_at: "2023-05-15T05:36:47.000000Z"
            },
            {
              id: 5,
              name: "Noodles",
              image: "noodles.png",
              parent_id: null,
              position: null,
              status: 1,
              priority: 1,
              slug: "noodles",
              created_at: "2023-05-15T05:36:47.000000Z",
              updated_at: "2023-05-15T05:36:47.000000Z"
            },
            {
              id: 6,
              name: "Drinks",
              image: "drinks.png",
              parent_id: null,
              position: null,
              status: 1,
              priority: 1,
              slug: "drinks",
              created_at: "2023-05-15T05:36:47.000000Z",
              updated_at: "2023-05-15T05:36:47.000000Z"
            },
            {
              id: 7,
              name: "Rice",
              image: "rice.png",
              parent_id: null,
              position: null,
              status: 1,
              priority: 1,
              slug: "rice",
              created_at: "2023-05-15T05:36:47.000000Z",
              updated_at: "2023-05-15T05:36:47.000000Z"
            },
            {
              id: 8,
              name: "Chicken",
              image: "chicken.png",
              parent_id: null,
              position: null,
              status: 1,
              priority: 1,
              slug: "chicken",
              created_at: "2023-05-15T05:36:47.000000Z",
              updated_at: "2023-05-15T05:36:47.000000Z"
            },
            {
              id: 9,
              name: "Salad",
              image: "salad.png",
              parent_id: null,
              position: null,
              status: 1,
              priority: 1,
              slug: "salad",
              created_at: "2023-05-15T05:36:47.000000Z",
              updated_at: "2023-05-15T05:36:47.000000Z"
            },
            {
              id: 10,
              name: "Fries",
              image: "fries.png",
              parent_id: null,
              position: null,
              status: 1,
              priority: 1,
              slug: "fries",
              created_at: "2023-05-15T05:36:47.000000Z",
              updated_at: "2023-05-15T05:36:47.000000Z"
            },
            {
              id: 11,
              name: "Dessert",
              image: "dessert.png",
              parent_id: null,
              position: null,
              status: 1,
              priority: 1,
              slug: "dessert",
              created_at: "2023-05-15T05:36:47.000000Z",
              updated_at: "2023-05-15T05:36:47.000000Z"
            }
        ]
    },
    mutattions: {},
    actions: {}
})